import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { BrandHeader } from "@/components/brand-header";
import { BrandColors } from "@/constants/theme";

const starterPosts=[
  {id:"1",name:"Francis",flag:"🇩🇪",place:"Paris, France",message:"The sunset view from Montmartre was unforgettable. Add it to your list!",likes:24},
  {id:"2",name:"Jan",flag:"🇳🇱",place:"Kyoto, Japan",message:"Three quiet temples worth visiting before 9am: Nanzen-ji, Kennin-ji, and Kōdai-ji.",likes:18},
  {id:"3",name:"Alex",flag:"🇺🇸",place:"Nice, France",message:"Walk the coastal path around sunset, then explore the old town for dinner.",likes:31},
];

export default function MessageBoardScreen(){const [posts,setPosts]=useState(starterPosts);const [message,setMessage]=useState("");const publish=()=>{const text=message.trim();if(!text)return;setPosts(current=>[{id:`local-${Date.now()}`,name:"You",flag:"🌍",place:"Travel update",message:text,likes:0},...current]);setMessage("")};return <SafeAreaView style={s.safe} edges={["top"]}><View style={s.header}><BrandHeader/></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text style={s.title}>Message Board</Text><Text style={s.subtitle}>Share discoveries with fellow travelers.</Text><View style={s.composer}><TextInput value={message} onChangeText={setMessage} placeholder="Share a travel tip or memory…" placeholderTextColor={BrandColors.muted} multiline style={s.input}/><TouchableOpacity style={[s.postButton,!message.trim()&&s.disabled]} disabled={!message.trim()} onPress={publish}><Ionicons name="send" size={18} color={BrandColors.white}/><Text style={s.postText}>Post</Text></TouchableOpacity></View>{posts.map(post=><View key={post.id} style={s.card}><View style={s.postHeader}><View style={s.avatar}><Ionicons name="person" size={21} color={BrandColors.onDark}/><Text style={s.flag}>{post.flag}</Text></View><View style={{flex:1}}><Text style={s.name}>{post.name}</Text><Text style={s.place}>{post.place}</Text></View><TouchableOpacity onPress={()=>Alert.alert("Post options","Report, mute, and save options will appear here.")}><Ionicons name="ellipsis-horizontal" size={20} color={BrandColors.onDarkMuted}/></TouchableOpacity></View><Text style={s.message}>{post.message}</Text><View style={s.actions}><TouchableOpacity onPress={()=>setPosts(current=>current.map(item=>item.id===post.id?{...item,likes:item.likes+1}:item))} style={s.action}><Ionicons name="heart-outline" size={18} color={BrandColors.copper}/><Text style={s.actionText}>{post.likes}</Text></TouchableOpacity><TouchableOpacity onPress={()=>Alert.alert("Reply",`Reply to ${post.name} is ready for the full community backend.`)} style={s.action}><Ionicons name="chatbubble-outline" size={17} color={BrandColors.copper}/><Text style={s.actionText}>Reply</Text></TouchableOpacity></View></View>)}</ScrollView></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.green},header:{paddingHorizontal:18},content:{padding:14,paddingTop:2,paddingBottom:35},title:{textAlign:"center",fontFamily:"PlayfairDisplay_700Bold",fontSize:32,color:BrandColors.onDark},subtitle:{marginTop:3,textAlign:"center",fontFamily:"Lora_400Regular",fontSize:11,color:BrandColors.onDarkMuted},composer:{marginTop:18,padding:12,borderWidth:1,borderColor:BrandColors.paleGreen,borderRadius:14,backgroundColor:"rgba(10,43,32,.35)"},input:{minHeight:68,fontFamily:"Lora_400Regular",fontSize:13,lineHeight:19,color:BrandColors.onDark,textAlignVertical:"top"},postButton:{alignSelf:"flex-end",height:36,paddingHorizontal:14,borderRadius:18,backgroundColor:BrandColors.copper,flexDirection:"row",alignItems:"center",gap:6},disabled:{opacity:.45},postText:{fontFamily:"Lora_700Bold",fontSize:11,color:BrandColors.white},card:{marginTop:12,padding:14,borderWidth:1,borderColor:BrandColors.paleGreen,borderRadius:14,backgroundColor:"rgba(10,43,32,.22)"},postHeader:{flexDirection:"row",alignItems:"center",gap:10},avatar:{width:42,height:42,borderRadius:21,backgroundColor:BrandColors.paleGreen,alignItems:"center",justifyContent:"center"},flag:{position:"absolute",right:-5,bottom:-3,fontSize:15},name:{fontFamily:"Lora_700Bold",fontSize:13,color:BrandColors.copper},place:{fontFamily:"Lora_400Regular",fontSize:9,color:BrandColors.onDarkMuted},message:{marginTop:12,fontFamily:"Lora_400Regular",fontSize:12,lineHeight:18,color:BrandColors.onDark},actions:{marginTop:12,paddingTop:10,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:BrandColors.paleGreen,flexDirection:"row",gap:22},action:{flexDirection:"row",alignItems:"center",gap:5},actionText:{fontFamily:"Lora_600SemiBold",fontSize:10,color:BrandColors.onDarkMuted}})
